version: "3.8"

services:
  postgres:
    container_name: $DB_CONTAINER_NAME
    build: ./src/scripts
    restart: always
    image: postgres:15
    environment:
      POSTGRES_USER: $USERNAME
      POSTGRES_PASSWORD: $PASSWORD
      POSTGRES_DB: $DATABASE
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - ${PORT}:${PORT}

volumes:
  db_data:
