version: "3.8"

services:
#  reverse-proxy:
#    container_name: $PROXY_CONTAINER_NAME
#    image: nginx:latest
#    ports:
#      - 80:80
#    depends_on:
#      - postgres
#    volumes:
#      - ./packages/config/nginx.conf:/etc/nginx/nginx.conf
#    extra_hosts:
#      - "host.docker.internal:host-gateway"

  postgres:
    container_name: $DB_CONTAINER_NAME
    build: ./src/scripts
    restart: always
    image: postgres:15
    environment:
      POSTGRES_USER: $USERNAME
      POSTGRES_PASSWORD: $PASSWORD
      POSTGRES_DB: $DATABASE
    volumes:
#      - ./src/scripts/seed.js:/scripts/seed.js
#      - ./src/scripts/init.sh:/scripts/init.sh
      - db_data:/var/lib/postgresql/data
    ports:
      - ${PORT}:${PORT}

volumes:
  db_data:
